# Generated by Django 5.2.3 on 2025-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='myapp',
            table='myappusers',
        ),
    ]
