# Generated by Django 5.2.3 on 2025-07-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_myapp_password_alter_myapp_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'managed': False},
        ),
    ]
