# Generated by Django 5.2.3 on 2025-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_myapp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
