# Generated by Django 5.2.3 on 2025-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_myemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyadminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('AdminPassword', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'adminUsers',
                'managed': False,
            },
        ),
    ]
