# Generated by Django 5.2.3 on 2025-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_myadminusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('GENDER', models.CharField(max_length=128)),
                ('AADHAR_NO', models.CharField(max_length=128)),
                ('PHONE_NUMBER', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
    ]
